### ISSUE TITLE
Panic on DiscoverOffer

### ISSUE THREAD

**Issue by mgazza** [insomniacslk/dhcp#468]
When calling discover offer the library panics with 
```
panic: runtime error: index out of range [9] with length 4

goroutine 4 [running]:
github.com/insomniacslk/dhcp/dhcpv4/nclient4.ipv4.protocol(...)
	/Users/markgascoyne/go/pkg/mod/github.com/insomniacslk/dhcp@v0.0.0-20220504074936-1ca156eafb9f/dhcpv4/nclient4/ipv4.go:108
github.com/insomniacslk/dhcp/dhcpv4/nclient4.ipv4.transportProtocol(...)
	/Users/markgascoyne/go/pkg/mod/github.com/insomniacslk/dhcp@v0.0.0-20220504074936-1ca156eafb9f/dhcpv4/nclient4/ipv4.go:124
github.com/insomniacslk/dhcp/dhcpv4/nclient4.(*BroadcastRawUDPConn).ReadFrom(0x1400000e138, {0x14000180000, 0x5dc, 0x0?})
	/Users/markgascoyne/go/pkg/mod/github.com/insomniacslk/dhcp@v0.0.0-20220504074936-1ca156eafb9f/dhcpv4/nclient4/conn_unix.go:115 +0x368
github.com/insomniacslk/dhcp/dhcpv4/nclient4.(*Client).receiveLoop(0x14000116120)
	/Users/markgascoyne/go/pkg/mod/github.com/insomniacslk/dhcp@v0.0.0-20220504074936-1ca156eafb9f/dhcpv4/nclient4/client.go:262 +0x90
created by github.com/insomniacslk/dhcp/dhcpv4/nclient4.new
	/Users/markgascoyne/go/pkg/mod/github.com/insomniacslk/dhcp@v0.0.0-20220504074936-1ca156eafb9f/dhcpv4/nclient4/client.go:223 +0x3c0
```

```go
package main

import (
	"context"
	"fmt"
	"github.com/insomniacslk/dhcp/dhcpv4/nclient4"
)

func main() {
	c, err := nclient4.New("en0")
	c.DiscoverOffer(context.TODO())
}
```

**Comment by pmazzini** [comment]
Fixed in #507
